##################################################################################
#' Partial Dependence Plot for a Species x BCR x Predictor
#'
#' Generates a partial dependence plot displaying
#' how bird density changes over the range of a model predictor for a given species and BCR.
#'
#'
#'
#' @param species A \code{character} specifying the species to generate a partial dependence plot for.
#' See \code{data(spp_tbl)} for available species and their spelling.
#'
#' @param predictor A \code{character} specifying the model predictor (e.g., temperature, precipitation)
#' to be visualized in the partial dependence plot. See \code{data(predictor_meta)} for available predictors.
#'
#' @param version A \code{character}, either \code{"v4"} or \code{"v5"}.
#' Defaults to \code{"v5"}.
#'
#' @param colour A \code{character} specifying the colour of the fitted spline.
#' Default is \code{"purple"}.
#'
#' @return A \code{ggplot} showing the partial dependence plot, including the
#' mean response and an error ribbon representing the 95% confidence interval.
#'
#' @details
#' This function fits a \code{smooth.spline()} to bootstrap replicates of the
#' bird density versus predictor relationship generated by \code{gbm::plot.gbm()},
#' with \code{continuous.resolution = 50}.
#' It then and visualizes the mean response across 32 bootstraps
#' with 95% confidence interval.
#' Note that partial dependence plots are generated only for species x BCR x predictor
#' combinations in the top 75 percentile of relative influence across all models.
#' Run (e.g. for V5) \code{arrange(bam_predictor_importance_v5, desc(mean_rel_inf))}
#' to view predictors with meaningful correlation with occurrence for a given species x BCR.
#'
#'
#' @importFrom dplyr bind_rows group_by summarise
#' @importFrom tidyr pivot_longer
#' @importFrom ggplot2 ggplot aes geom_boxplot geom_jitter geom_line geom_ribbon labs theme_minimal
#' @importFrom stats smooth.spline predict quantile
#'
#' @export
#'
#' @examples
#' bam_partial_dependence("ALFL", "can10", "ERAMAP_1km", "v5")
#'
#'
##################################################################################


bam_partial_dependence <- function(species, bcr, predictor, version="v5", colour="purple") {

  if (!version %in% c("v4", "v5")) {
    stop("Invalid version argument. Must be either 'v4' or 'v5'.")
  }

  # load boot_pts_sorted_v* from data folder
  if (version == "v5") {
    #data("boot_pts_sorted_v5", package = "BAMexploreR")
    data <- bam_predictor_response_v5
  } else {
    data <- bam_predictor_response_v4
  }


  # convert user specified species to FLBCs
  # checks for spellings and returns message if not found
  species <- standardize_species_names(species_input = species, spp_tbl = BAMexploreR:::spp_tbl)


  # check if the key exists in the data
  if (!any(data$species == species & data$bcr == bcr & data$var == predictor)) {
    stop("The specified combination of species, bcr, and predictor is below the 75% percentile
    of relative predictor importance. No plot will be generated.
    Run `arrange(bam_predictor_importance_v5, desc(mean_rel_inf))`
    to view predictors with meaningful correlation with bird abundance. ")
  }

  # filter bootstraps for the relavent species X BCR x covariate
  combined_df <- filter(data, species == !!species, bcr == !!bcr, var == !!predictor)

  # for categorical predictors generate a boxplot
  if (any(combined_df$covariate_type == "categorical")) {
    ggplot(combined_df, aes(x = covariate_value, y = y)) +
      geom_jitter(width = 0.2, alpha = 0.8, size = 1, color = colour) +
      geom_boxplot(fill=colour, alpha=0.4, outlier.shape = NA) +
      labs(title = paste("Partial Dependence (Categorical):", species, bcr, predictor),
           x = predictor, y = "Singing males per ha") +
      theme_minimal()
  } else {

  # for continuous predictors generate a line plot
  # create a vector of x values (covering the domain of the combined bootstraps) for prediction by `smooth.spline()`
  x_grid <- seq(min(combined_df$covariate_value), max(combined_df$covariate_value), length.out = 1000)


  # fit a smoothing function to each bootstrap replicate and predict over the domain of x values
  predictions <-
    combined_df |>
    group_split(replicate) |>
    map(~ {
      fit <- smooth.spline(.x$covariate_value, .x$y)
      predict(fit, x_grid)$y
    })

  # combine predictions into a data frame
  prediction_df <- do.call(cbind, predictions)

  # simplify column names
  colnames(prediction_df) <- paste0("replicate_", seq_along(predictions))
  prediction_df <- as_tibble(prediction_df)
  prediction_df$covariate_value <- x_grid

  # calculate summary statistics (mean and error bounds) for each x value
  summary_df <-
    prediction_df |>
    pivot_longer(cols = starts_with("replicate_"), names_to = "replicate", values_to = "predicted_response") |>
    group_by(covariate_value) |>
    summarise(
      mean_response = mean(predicted_response),
      lower_bound = quantile(predicted_response, 0.025),
      upper_bound = quantile(predicted_response, 0.975)
    )

  # plot partial dependence with error envelope
  ggplot(summary_df, aes(x = covariate_value, y = mean_response)) +
    geom_line(colour = colour) +
    geom_ribbon(aes(ymin = lower_bound, ymax = upper_bound), alpha = 0.2, fill = colour) +
    labs(title = paste("Partial Dependence Plot for", species, "in BCR", bcr, "and Predictor", predictor),
         x = predictor, y = "singing males per Ha") +
    theme_minimal()
 }

}
